const ACTION_SAVE_FAVORITES = 'ACTION_SAVE_FAVORITES';
const ACTION_EDIT_FAVORITES = 'ACTION_EDIT_FAVORITES';
const ACTION_DELETE_FAVORITES = 'ACTION_DELETE_FAVORITES';

export { ACTION_SAVE_FAVORITES, ACTION_EDIT_FAVORITES, ACTION_DELETE_FAVORITES, };
