const ACTION_GET_VIDEO_STATISTICS = 'ACTION_GET_VIDEO_STATISTICS';
const ACTION_RESET_VIDEO_STATISTICS = 'ACTION_RESET_VIDEO_STATISTICS';

export { ACTION_GET_VIDEO_STATISTICS, ACTION_RESET_VIDEO_STATISTICS };
